services:
  ollama:
    image: ollama/ollama
    container_name: local_ollama
    volumes:
      - ./data:/root/.ollama
    ports:
      - "11434:11434"
networks:
  iteams_network:
    name: iteams_network
    external: true